### ISSUE TITLE
how to execute DML on fabricated objects

### ISSUE THREAD

**Issue by kunalkhattry** [mattaddy/SObjectFabricator#28]
I was trying to use this for performing unit tests in my org. So the code that I was trying to test had some SOQLs & DMLs. I do understand that the fabricated records cannot be queried using a SOQL and am bypassing it using some logic. However I do have questions on how do we handle the DMLs, since it is required for the unit test to run successfully.
Is there some other library or package that we need to install to handle the DMLs on fabricated objects?

**Comment by bobalicious** [comment]
Correct.

SObject Fabricator is not designed to (currently) be used where DML is involved.

If you want to create and update data in your database, then you need to put data into your database - consider looking at something like Apex Domain Builder: https://github.com/rsoesemann/apex-domainbuilder

However - if you can mock the DML (E.g. if you can use a class to write the data instead of using Salesforce's DML statements directly), and you can get away without hitting the database *at all*, then you can continue use SObject Fabricator.  If this doesn't make sense, then I probably can't help you further - and I'd direct you to Apex Domain Builder for cases where DML is involved and cannot be avoided.
